package frc.robot.utils;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.RobotController;
import frc.robot.Ports;


// Generated by the 2026 Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class TunerConstants {


    // COMMAND-USED CONSTANTS
    public static double MaxSpeed = 5; //1.0  * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond); // kSpeedAt12Volts desired top speed
    public static double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond); // 3/4 of a rotation per second max angular velocity

     /* Setting up bindings for necessary control of the swerve drive platform */
    public static final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric()
            .withDeadband(MaxSpeed * 0.1).withRotationalDeadband(MaxAngularRate * 0.1) // Add a 10% deadband
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage); // Use open-loop control for drive motors
    public static final SwerveRequest.SwerveDriveBrake brake = new SwerveRequest.SwerveDriveBrake();
    public static final SwerveRequest.PointWheelsAt point = new SwerveRequest.PointWheelsAt();
//

    private static Slot0Configs driveGains;
    private static Slot0Configs steerGains;
    public static double kSrot = 0;
    public static double kVrot = 0; 
    public static double kArot = 0;
    public static Pigeon2Configuration pigeonConfigs;
        

    // Check if Roborio is for the Competition Robot
    public static final String COMPETITION_ROBORIO_SERIAL_NUM = "0329F2C4"; // ID for Current Roborio v2 on COMPBOT
    public static boolean isCompetitionBot() {
        String serialNumber = RobotController.getSerialNumber();
        System.out.println("ROBORIO is " + serialNumber);
        if (serialNumber.equals(COMPETITION_ROBORIO_SERIAL_NUM)) {
            System.out.println("Competition Bot RoboRio found!");
            return true;
        }
        System.out.println("Practice bot!");
        return false; 
    }

    // VARIABLES THAT CHANGE BETWEEN VERSIONS OF ROBOT
    static {

        // COMPETITION BOT
        if (isCompetitionBot()) {

            // COMPBOT ENCODER OFFSETS (from Phoenix)
            kFrontLeftEncoderOffset = Rotations.of(0.178466796875);
            kFrontRightEncoderOffset = Rotations.of(-0.237548828125);
            kBackLeftEncoderOffset = Rotations.of(-0.35400390625);
            kBackRightEncoderOffset = Rotations.of(-0.279052734375);

            // COMPBOT PIGEON CONFIG
            pigeonConfigs = new Pigeon2Configuration()
            .withMountPose(new MountPoseConfigs()
            .withMountPosePitch(-0.7408755421638489)
            .withMountPoseRoll(-0.03825372830033302)
            .withMountPoseYaw(0.31220224499702454));

            // COMPBOT DRIVE GAINS (from SYSID)
            driveGains = new Slot0Configs()
                .withKP(0.1).withKI(0).withKD(0)
                .withKS(0.26131)
                .withKV(0.12185)
                .withKA(0.0018321);

            // COMPBOT STEER/TURN GAINS (from SYSID)
            steerGains = new Slot0Configs()
                .withKP(100).withKI(0).withKD(0.5)
                .withKS(0.44889)
                .withKV(2.5504)
                .withKA(0.039283);

            // COMPBOT ROTATION GAINS FROM SYSID
            // kSrot = 0.15; // Replace with your Rotation kS
            // kVrot = 0.12; // Replace with your Rotation kV
            // kArot = 0.01; // Replace with your Rotation kA
            }

            
         else {

            // BACKUPBOT ENCODER OFFSETS (from Phoenix)
            kFrontLeftEncoderOffset = Rotations.of(-0.139404296875);
            kFrontRightEncoderOffset = Rotations.of(-0.064208984375);
            kBackLeftEncoderOffset = Rotations.of(0.438720703125);
            kBackRightEncoderOffset = Rotations.of(0.353515625);

            // BACKUPBOT PIGEON CONFIG
            pigeonConfigs = new Pigeon2Configuration()
            .withMountPose(new MountPoseConfigs()
            .withMountPosePitch(-0.7408745288848877)
            .withMountPoseRoll(-0.03825372830033302)
            .withMountPoseYaw(0.31220224499702454));
            
            // BACKUPBOT DRIVE GAINS (from SYSID)
            driveGains = new Slot0Configs()
                .withKP(0.1).withKI(0).withKD(0)
                .withKS(0.26131)  // <-- Replace with Translation kS
                .withKV(0.12185) // <-- Replace with Translation kV
                .withKA(0.0018321); // <-- Replace with  Translation kA

            // BACKUPBOT STEER/TURN GAINS (from SYSID)
            steerGains = new Slot0Configs()
                .withKP(100).withKI(0).withKD(0.5)
                .withKS(0.33066)   // <-- Replace with Steer kS
                .withKV(2.5268)  // <-- Replace with Steer kV
                .withKA(0.023705); // <-- Replace with Steer kA

            // BACKUPBOT ROTATION GAINS FROM SYSID
            // kSrot = 0.15; // Replace with your Rotation kS
            // kVrot = 0.12; // Replace with your Rotation kV
            // kArot = 0.01; // Replace with your Rotation kA
        }


    }


    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.Voltage;

    // The type of motor used for the drive motor
    private static final DriveMotorArrangement kDriveMotorType = DriveMotorArrangement.TalonFX_Integrated;
    // The type of motor used for the drive motor
    private static final SteerMotorArrangement kSteerMotorType = SteerMotorArrangement.TalonFX_Integrated;

    // The remote sensor feedback type to use for the steer motors;
    // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
    private static final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.FusedCANcoder;

    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    private static final Current kSlipCurrent = Amps.of(120);

    // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
    private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration();
    private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                // Swerve azimuth does not require much torque output, so we can set a relatively low
                // stator current limit to help avoid brownouts without impacting performance.
                .withStatorCurrentLimit(Amps.of(60))
                .withStatorCurrentLimitEnable(true)
        );
    private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
    
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs


    // CAN bus that the devices are located on;
    // All swerve devices must share the same CAN bus
    public static final CANBus CAN_DRIVE_BUS = new CANBus("SwerveBus", "./logs/example.hoot");

    // Theoretical free speed (m/s) at 12 V applied output;
    // This needs to be tuned to your individual robot
    public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(6.11); //4.54 in example code

    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
    // This may need to be tuned to your individual robot
    private static final double kCoupleRatio = 0;

    private static final double kDriveGearRatio = 4.421052631578947; //Swerve X2S (X2 19T:28T --> 20.73 ft/s)
    private static final double kSteerGearRatio = 25.9; //Consistent across all WCP X2 Swerves
    private static final Distance kWheelRadius = Inches.of(1.75);   //Diameter of 3.5 inch wheel

    private static final boolean kInvertLeftSide = true;
    private static final boolean kInvertRightSide = false;
            


    // These are only used for simulation
    private static final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.01);
    private static final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.01);
    // Simulated voltage necessary to overcome friction
    private static final Voltage kSteerFrictionVoltage = Volts.of(0.2);
    private static final Voltage kDriveFrictionVoltage = Volts.of(0.2);


    private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator =
        new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
            .withDriveMotorGearRatio(kDriveGearRatio)
            .withSteerMotorGearRatio(kSteerGearRatio)
            .withCouplingGearRatio(kCoupleRatio)
            .withWheelRadius(kWheelRadius)
            .withSteerMotorGains(steerGains)
            .withDriveMotorGains(driveGains)
            .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
            .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
            .withSlipCurrent(kSlipCurrent)
            .withSpeedAt12Volts(kSpeedAt12Volts)
            .withDriveMotorType(kDriveMotorType)
            .withSteerMotorType(kSteerMotorType)
            .withFeedbackSource(kSteerFeedbackType)
            .withDriveMotorInitialConfigs(driveInitialConfigs)
            .withSteerMotorInitialConfigs(steerInitialConfigs)
            .withEncoderInitialConfigs(encoderInitialConfigs)
            .withSteerInertia(kSteerInertia)
            .withDriveInertia(kDriveInertia)
            .withSteerFrictionVoltage(kSteerFrictionVoltage)
            .withDriveFrictionVoltage(kDriveFrictionVoltage);


    // Front Left
    private static Angle kFrontLeftEncoderOffset;
    private static final boolean kFrontLeftSteerMotorInverted = false;
    private static final boolean kFrontLeftEncoderInverted = false;
    private static final Distance kFrontLeftXPos = Inches.of(10.25);
    private static final Distance kFrontLeftYPos = Inches.of(13.75);

    // Front Right
    private static Angle kFrontRightEncoderOffset;
    private static final boolean kFrontRightSteerMotorInverted = false;
    private static final boolean kFrontRightEncoderInverted = true;
    private static final Distance kFrontRightXPos = Inches.of(10.25);
    private static final Distance kFrontRightYPos = Inches.of(-13.75);

    // Back Left
    private static Angle kBackLeftEncoderOffset;
    private static final boolean kBackLeftSteerMotorInverted = false;
    private static final boolean kBackLeftEncoderInverted = true;
    private static final Distance kBackLeftXPos = Inches.of(-10.25);
    private static final Distance kBackLeftYPos = Inches.of(13.75);

    // Back Right
    private static Angle kBackRightEncoderOffset;
    private static final boolean kBackRightSteerMotorInverted = false;
    private static final boolean kBackRightEncoderInverted = true;
    private static final Distance kBackRightXPos = Inches.of(-10.25);
    private static final Distance kBackRightYPos = Inches.of(-13.75);



    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeftModule =
        ConstantCreator.createModuleConstants(
            Ports.SWERVE_TURN_FL, Ports.SWERVE_DRIVE_FL, Ports.SWERVE_ANGLE_FL, kFrontLeftEncoderOffset,
            kFrontLeftXPos, kFrontLeftYPos, kInvertLeftSide, kFrontLeftSteerMotorInverted, kFrontLeftEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRightModule =
        ConstantCreator.createModuleConstants(
            Ports.SWERVE_TURN_FR, Ports.SWERVE_DRIVE_FR, Ports.SWERVE_ANGLE_FR, kFrontRightEncoderOffset,
            kFrontRightXPos, kFrontRightYPos, kInvertRightSide, kFrontRightSteerMotorInverted, kFrontRightEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeftModule =
        ConstantCreator.createModuleConstants(
            Ports.SWERVE_TURN_BL, Ports.SWERVE_DRIVE_BL, Ports.SWERVE_ANGLE_BL, kBackLeftEncoderOffset,
            kBackLeftXPos, kBackLeftYPos, kInvertLeftSide, kBackLeftSteerMotorInverted, kBackLeftEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRightModule =
        ConstantCreator.createModuleConstants(
            Ports.SWERVE_TURN_BR, Ports.SWERVE_DRIVE_BR, Ports.SWERVE_ANGLE_BR, kBackRightEncoderOffset,
            kBackRightXPos, kBackRightYPos, kInvertRightSide, kBackRightSteerMotorInverted, kBackRightEncoderInverted
        );


    public static SwerveDrivetrainConstants drivetrainConstants = new SwerveDrivetrainConstants()
        .withCANBusName(TunerConstants.CAN_DRIVE_BUS.getName())
        .withPigeon2Id(Ports.PIGEON)
        .withPigeon2Configs(TunerConstants.pigeonConfigs);


}
